config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :venues do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[create]
    collection do
      get :top
    end
  end
  get "/booking/:id", to: "bookings#confirmation", as: "confirmation"
  get "/dashboard", to: "dashboards#show", as: "dashboard"
  resources :users, only: [] do
    member do
      patch :owner
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  has_one :review, dependent: :destroy

  validates :start_time, :end_time, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :venues, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :first_name, :last_name, length: { minimum: 2 }
  
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  belongs_to :user
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :name, :location, :description, :price, presence: true
  validates :name, length: { minimum: 4 }
  validates :description, length: { minimum: 20 }

  def average_rating
    ratings = reviews.map do |review|
      review.rating
    end
    if reviews.present?
    average = ratings.sum / ratings.length
    else
    average = 0
    end
    return average
  end

  def self.top_three
    Venue.all.sort {|a,b| b.average_rating <=> a.average_rating}.first(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @venue = Venue.find(params[:venue_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    # we need `venue_id` to associate review with corresponding restaurant
    @venue = Venue.find(params[:venue_id])
    @booking.venue = @venue
    @booking.user = current_user
    if @booking.save!
      redirect_to confirmation_path(@booking)
    else
      render :new
    end
  end

  def confirmation
    @booking = Booking.find(params[:id])
    @venue = @booking.venue
    @booking.total_price = (@booking.end_time.hour - @booking.start_time.hour) * @venue.price
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :total_price)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user
    @user.owner = true unless @user.venues.empty?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
    @display_top = Venue.top_three
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # /venues/:venue_id/reviews

  def create
    @review = Review.new(reviews_params)
    @review.venue = Venue.find(params[:venue_id])
    if @review.save!
      redirect_to review_path(@review)
    else
      render 'venues/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :venue)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def owner
        current_user.owner = true
        current_user.save
        redirect_to dashboard_path
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @venues = Venue.geocoded
    @markers = @venues.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { venue: venue }),
      }
    end
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save!
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def show
    @venue = Venue.find(params[:id])
    @review = Review.new(id: @venue)
    @booking = Booking.new

    @markers = [{
        lat: @venue.latitude,
        lng: @venue.longitude,
      }]
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :location, :description, :price, :user, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/views/bookings/confirmation.html.erb
<div class="containerConfirmation">
<li>
    <h1 class="headConfirmation">Your Reservation is confirmed!</h1>
    <h2>See Reservation Details:</h2>
    <p>Name of the Venue: <%= @venue.name %></p>
    <p>Location: <%= @venue.location %></p>
    <p>Total Price: <%= @booking.total_price %>€</p>

    <p>Thank You for booking with Photostra! Enjoy your Photoshoot</p>

    <%= link_to "See other venues", venues_path, class: "btn btn-dark btn-lg" %>
    </li>
</div>

app/views/bookings/new.html.erb
<div class="containerBooking">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h1>Booking Details for <div class="titleBooking"><%= @venue.name %></div></h1>
    <p>Price will be charged per hour, the current price per hour is <span class="currentPrice"><%= @venue.price %>€</span>.</p>
    <p class="lineBeforeForm"> This location is <span class="availabilityText">available</span> for the requested time!</p>
    </div>

  <div class="containerCalendar">
    <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
      <h2>Choose Timeslot</h2>
      <%= simple_form_for [@venue, @booking] do |f| %>
        <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.submit "Request Booking", class: "btn btn-dark btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<h1 class="h1-dashboard text-center mb-3">Welcome <%= @user.first_name %></h1>
<% if @user.owner %>
  <div class="text-center"><%= link_to "Make a new venue", new_venue_path, class: "btn btn-secondary mt-5 visible"%></div>
  <% else %>
    <div class="text-center"><%= link_to "Become an owner", owner_user_path(@user), method: :patch, class: "btn btn-secondary mt-5" %></div>
<% end %>
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-chat/ava3.png" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">

            <h5 class="my-3"><%= @user.first_name + " "+ @user.last_name %></h5>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
            
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">www.github.com</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                <p class="mb-0">https://twitter.com</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                <p class="mb-0">https://facebook.com</p>

              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">First Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name%></p>

              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">

                <p class="mb-0">Last Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.last_name%></p>
              </div>
            </div>
            
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email%></p>

              </div>
            </div>
          </div>
        </div>
         
           <ul class="nav nav-tabs" id="myTab" role="tablist">
             <li class="nav-item">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Bookings</a>
                  </li>
                 <% if @user.owner %>
                   <li class="nav-item">
                     <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Venues</a>
                   </li>
                 <% end %>
            </ul>
               <div class="tab-content" id="myTabContent">
                 <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">     
                    <div class="row">
                      <div class="col-md-12">
                        <div class="card mb-4 mb-md-0">
                          <div class="card-body">
                            <% @user.bookings.each do |booking| %>
                            <%= link_to venue_path(booking.venue), class:'text-decoration-none' do %>
                              <div class="card-product">
                                  <%= image_tag booking.venue.photos.first%>
                                    <div class="card-product-infos">
                                      <h2><%= booking.venue.name %></h2>
                                      <p><%= booking.start_time %></p>
                                    </div>
                              </div>
                            <% end %>
                           <% end %>
                          </div>
                        </div>
                      </div>
                  </div>


                </div>
                 <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                 
                  <% if @user.owner %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="card mb-4 mb-md-0">
                          <div class="card-body">
                            <% @user.venues.each do |venue| %>
                            <%= link_to venue_path(venue), class:'text-decoration-none' do %>
                              <div class="card-product">
                                  <%= image_tag venue.photos.first%>
                                    <div class="card-product-infos">
                                      <h2><%= venue.name%></h2>
                                      <p><%= venue.description %></p>
                                    </div>
                               </div>
                            <% end %>
                           <% end %>
                          </div>
                        </div>
                      </div>
                  </div>
              <% end %>
         </div>
            
  </div>
</section>

           

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div id="page-container">
        <%= render 'shared/navbar' %>

        <%= yield %>

        <%= render 'shared/flashes' %>
        <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<header>
  <div class="informationHome">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item banner active backgroundImage1">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Photora</h2>
            <p class="lead">Rent unique locations for your photoshoot</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item banner backgroundImage2">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Photora</h2>
            <p class="lead">Rent unique locations for your photoshoot</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item banner backgroundImage3" >
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Photora</h2>
            <p class="lead">Rent unique locations for your photoshoot</p>
          </div>
        </div>
        <div class="carousel-item banner backgroundImage4" >
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Photora</h2>
            <p class="lead">Rent unique locations for your photoshoot</p>
          </div>
        </div>
        <div class="carousel-item banner backgroundImage5">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Photora</h2>
            <p class="lead">Rent unique locations for your photoshoot</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <h2 class="subheaderHome">Get inspired by our TOP 3 Locations</h2>
    <div class="cards-container" style="width: 80vw; margin: 40px auto;">
    <% @display_top.each do |venue| %>
    <div class="card-venue" >
      <%= link_to venue_path(venue), class:"text-decoration-none" do %>
      <%= image_tag venue.photos.first, class:"card-img-top card-venue-img pictureIndex"%>
      <div class="card-body">
        <h5 class="card-title title"><%= venue.name %></h5>
        <h5 class="cardLocation"><%= venue.location %></h5>
        <% if venue.average_rating.zero? %>
          <small><em class="text-muted">no reviews yet</em></small>
        <% else %>
        <% venue.average_rating.times do %>
        <i class="fas fa-star star-yellow starColor"></i>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
  </div>
</header>
  <div class="container">
  </div>

app/views/shared/_cards.html.erb
  <div class="card col-4" >
  <%# <img src="picture_1" class="card-img-top" alt="..."> %>
    <%= image_tag "picture_1.jpg", class:"cardPicture"%>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <h5 class="cardLocation">📍 Location</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-danger cardButton">Explore</a>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white" id="footer">
  <!-- Grid container -->
  <div class="container p-1">
    <!-- Section: Social media -->
    <section class="mb-2">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-2">
              <input type="email" id="form5Example21" class="form-control" placeholder="Email address">

            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-2">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->
  </div>
  <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">Photora</a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%# <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo1.png", class: "logo"%>
  <%# <% end %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Explore", venues_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/venue/new.html.erb
<h1>New Venue</h1>

<%= simple_form_for(@Venue) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }%>
  <%= f.submit %>
<% end %>

app/views/venues/_info_window.html.erb
<h2 class="popupName"><%= link_to venue.name, venue_path(venue), class:"linkingPopup"%></h2>
<p class="popupLocation">📍 <%= venue.location %></p>

app/views/venues/index.html.erb
<h1 class="headerIndex">Have a look at our unique locations</h1>
<div class="grid-mapIndex">
 <div class="cards-container ">
    <% @venues.each do |venue| %>
    <div class="card-venue" >
      <%= link_to venue_path(venue), class:"text-decoration-none" do %>
      <%= image_tag venue.photos.first, class:"card-img-top card-venue-img pictureIndex"%>
      <div class="card-body">
        <h5 class="card-title title"><%= venue.name %></h5>
        <h5 class="cardLocation"><%= venue.location %></h5>
        <% if venue.average_rating.zero? %>
          <small><em class="text-muted">no reviews yet</em></small>
        <% else %>
        <% venue.average_rating.times do %>
        <i class="fas fa-star star-yellow starColor"></i>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
  <div>
    <div id="map"
        style="height: 100vh; width: 27vw;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="parent-container d-flex">
    <div class="container">
        <div class="row">
            <div class="col p-5">
                <h1 class="text-center mt-5">New Venue</h1>
                    <%= simple_form_for(@venue) do |f| %>
                      <%= f.input :name %>
                      <%= f.input :location %>
                      <%= f.input :description %>
                      <%= f.input :price %>
                      <%= f.input :photos, as: :file, input_html: { multiple: true }%>
                      <%= f.submit %>
                    <% end %>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col">
              <img src="https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8aG9tZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" class="img-new" alt="Girl in a jacket" width="100%">
            </div>
        </div>
    </div>
</div>


  

app/views/venues/show.html.erb
<h1 class="showHeader"> <%= @venue.name %></h1>
    <div class="containerLocation">
      <p class="showLocation"> 📍 Location: <%= @venue.location %></p>
      <p class="card-price"> Price / hour: <%= @venue.price %>€</p>
    </div>

    <div class="top_show">
      <!-- Carousel -->
      <div>
        <div id="carouselExampleIndicators" class="carousel slide carousel-size" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag @venue.photos.first, class:"d-block w-100 pictureShow" %>
            </div>
            <div class="carousel-item">
              <%= image_tag @venue.photos.second, class:"d-block w-100 pictureShow" %>
            </div>
            <div class="carousel-item">
              <%= image_tag @venue.photos.last, class:"d-block w-100 pictureShow" %>
            </div>
          </div>
        </div>
        <br>
        <p class="showDescription"><%= @venue.description %></p>
        <br>
        <%= link_to "Book now!", new_venue_booking_path(@venue), class:"btn btn-dark btn-block rounded" %>
      </div>
      <!-- Carousel -->


      <!-- Reviews -->
      <div>

        <div class="wrapper">
          <div class="reviews">
            <h3>Reviews</h3>
            <% if @venue.reviews.empty? %>
              <small><em class="text-muted">Be the first one to review this venue</em></small>
            <% else %>
              <% @venue.reviews.first(5).each do |review| %>
                <div>
                  <% review.rating.times do %>
                    <i class="fas fa-star star-yellow"></i>
                  <% end %>
                  <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
                  <p class="mb-0"><%= review.content %></p>
                </div>
                <hr>
              <% end %>
            <% end %>
          </div>

        </div>
      </div>

      <!-- Reviews -->
    </div>



<div class="parent-container d-flex align-items-center">

    <!-- Map -->
    <div class="container">
      <div class="row">
        <div class="mapIndexShow col ">
          <div id="map2"
              style="width: 50vw; height: 350px"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>

      </div>
    </div>

    <!-- Map -->

    <div class="container">
      <div class="row">
        <div class="rev_form col bg-white rounded p-3">
          <h3>Add your review</h5>
          <%= simple_form_for [@venue, @review] do |f| %>
            <%= f.input :content, placeholder: 'Add your review here...' %>
            <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { id: 'review_rating' } %>
            <%= f.submit class:'btn btn-dark btn-lg rounded' %>
          <% end %>
        </div>

      </div>
    </div>

</div>